name: "Static Analysis"

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.php'
    types: [opened, reopened, synchronize]

jobs:
  self-test-and-phpstan:
    strategy:
      matrix:
        php: ["8.4"]
    name: PHP ${{ matrix.php }} Static Analysis

    runs-on: ubuntu-24.04
    env:
      APP_ENV: local
      APP_DEBUG: true

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, intl, zip, bcmath

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Basic .env
        run: | 
          echo "APP_URL=https://local.test" >> .env
          echo "DB_PASSWORD=123456" >> .env
          echo "REVERB_APP_ID=123456" >> .env
          echo "REVERB_APP_KEY=123456" >> .env
          echo "REVERB_APP_SECRET=123456" >> .env

      - name: Install Dependencies
        run: composer install

      - name: Laravel Key Generate
        run: php artisan key:generate

      - name: Laravel About
        run: php artisan about

      - name: Config Cache
        run: php artisan config:cache

      - name: View Cache
        run: php artisan view:cache

      - name: Route Cache
        run: php artisan route:cache

      - name: PHPStan
        run: php artisan stan
